name: Build and Deploy

on:
  push:
    branches:
      - release
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build and deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
          BRANCH: release
          FOLDER: build
          BUILD_SCRIPT: yarn install && yarn build
